# platform = multi_platform_all
# reboot = false
# strategy = disable
# complexity = low
# disruption = low
- name: Ensure xorg-x11-server is removed
  package:
    name: xorg-x11-server
    state: absent
  tags:
    - package_xorg_x11_server_removed
    - high_severity
    - disable_strategy
    - low_complexity
    - low_disruption
    - no_reboot_needed
