# platform = multi_platform_fedora,multi_platform_rhel,multi_platform_rhv,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Ensure daily rotate
  lineinfile:
    path: /etc/logrotate.conf
    regexp: '^daily'
    insertafter: 'EOF'
    line: daily
    state: present

- name: Remove weekly, monthly or yearly rotates
  lineinfile:
    dest: /etc/logrotate.conf
    regexp: "{{ item.regexp }}"
    state: absent
  with_items:
    - { regexp: '^weekly' }
    - { regexp: '^monthly' }
    - { regexp: '^yearly' }

- name: Set interpreter on daily cron
  lineinfile:
    dest: /etc/cron.daily/logrotate
    regexp: '^\#!\/bin\/.*sh'
    line: "#!/bin/sh"
    state: present
    insertafter: 'BOF'
    create: yes

- name: Configure daily cron
  lineinfile:
    path: /etc/cron.daily/logrotate
    regexp: '^\s*\/usr\/sbin\/logrotate\s.*\/etc\/logrotate\.conf'
    insertafter: 'EOF'
    state: present
    line: /usr/sbin/logrotate /etc/logrotate.conf
