# platform = multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Insert a the new rule before an existing rule in common-auth
  pamd:
    name: common-auth
    type: auth
    control: required
    module_path: pam_env.so
    new_type: auth
    new_control: required
    new_module_path: pam_tally2.so
    module_arguments: 'onerr=fail audit silent deny=5 unlock_time=900'
    state: before

- name: Replace all module arguments in the existing rule in common-auth
  pamd:
    name: common-auth
    type: auth
    control: required
    module_path: pam_tally2.so
    module_arguments: 'onerr=fail audit silent deny=5 unlock_time=900'
    state: updated



- name: Insert a the new rule before an existing rule in common-account
  pamd:
    name: common-account
    type: account
    control: required
    module_path: pam_unix.so
    new_type: account
    new_control: required
    new_module_path: pam_tally2.so
    state: before

- name: Replace all module arguments in the existing rule in common-account
  pamd:
    name: common-account
    type: account
    control: required
    module_path: pam_tally2.so
    module_arguments: ''
    state: updated


