# platform = multi_platform_fedora,multi_platform_rhel,multi_platform_rhv,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Ensure Log Level INFO
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '\#?LogLevel\s.+'
    line: LogLevel INFO
    state: present
  register: sshd

- name: Restart service SSHD
  service:
    name: sshd
    state: reloaded
  when: sshd.changed
