# platform = multi_platform_fedora,multi_platform_rhel,multi_platform_rhv,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Set variable ruta
  set_fact:
    ruta: "/etc/audit/audit.rules"

- name: Check if /etc/audit/rules.d exists
  stat:
    path: /etc/audit/rules.d
  register: stat_result

- name: Set variable if /etc/audit/rules.d exists
  set_fact:
    ruta: "/etc/audit/rules.d/sudoers.rules"
  when: stat_result.stat.exists == True

- name: Adding remediation to audit.rules
  blockinfile:
    path: "{{ ruta }}"
    create: yes
    block: |
      -w /etc/sudoers -p wa -k scope
      -w /etc/sudoers.d/ -p wa -k scope
    marker: "## {mark} ANSIBLE MANAGED BLOCK for mac_modification"

- name: Check if it's inmutable
  command: grep -qi "^\s*[^#]*-e 2" /etc/audit/audit.rules
  ignore_errors: True
  register: is_inmutable

- debug:
    msg: Reboot required
  when: is_inmutable.rc == 0

- name: Reload rules
  command: augenrules --load
  when: is_inmutable.rc == 1
