# platform = multi_platform_all,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- (xccdf-var var_accounts_user_umask)

- name: Set user umask in /etc/bash.bashrc
  replace:
      path: /etc/bash.bashrc
      regexp: "#*umask.*"
      replace: "umask {{ var_accounts_user_umask }}"
      backup  : yes
  register  : checkIfLineIsHere

# If the line not is here, I add it
- name: Add line
  lineinfile:
      state   : present
      dest    : /etc/bash.bashrc
      line    : "umask {{ var_accounts_user_umask }}"
      insertafter: EOF
  when: checkIfLineIsHere.changed == false

# If the line is here, I still want this line in the file, Then restore it
- name: Restore the searched line.
  lineinfile:
      state   : present
      dest    : /etc/bash.bashrc
      line    : "umask {{ var_accounts_user_umask }}"
  when: checkIfLineIsHere.changed
