# platform = multi_platform_fedora,multi_platform_rhel,multi_platform_rhv,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Set variable ruta
  set_fact:
    ruta: "/etc/audit/audit.rules"

- name: Check if /etc/audit/rules.d exists
  stat:
    path: /etc/audit/rules.d
  register: stat_result

- name: Set variable if /etc/audit/rules.d exists
  set_fact:
    ruta: "/etc/audit/rules.d/session_events.rules"
  when: stat_result.stat.exists == True

- name: Adding remediation to audit.rules
  blockinfile:
    path: "{{ ruta }}"
    create: yes
    block: |
      -w /var/log/faillog -p wa -k logins
      -w /var/log/lastlog -p wa -k logins
      -w /var/log/tallylog -p wa -k logins
    marker: "# {mark} ANSIBLE MANAGED BLOCK for session_events"

- name: Reload rules
  command: augenrules --load


