# platform = multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_rhv,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
### To set the users, please execute like ansible-playbook playbook.yml --extra-vars "users=***USER1 USER2***"

- name: Ensure limit user access set to a variable
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '\#?DenyUsers.*'
    line: DenyUsers {{ users }}
    state: present
  register: sshd

- name: Restart service SSHD
  service:
    name: sshd
    state: reloaded
  when: sshd.changed
