# platform = multi_platform_fedora,multi_platform_rhel,multi_platform_rhv,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Ensure Protocol 2
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Protocol\s2'
    insertafter: 'BOF'
    line: Protocol 2
    state: present
  register: sshd

- name: Restart service SSHD
  service:
    name: sshd
    state: restarted
  when: sshd.changed