# platform = multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_rhv,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
### To set the number to a variable, please execute like ansible-playbook playbook.yml --extra-vars "seconds=***desired seconds***"

- name: Ensure ClientAliveInterval set to variable
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '\#?ClientAliveInterval.*'
    line: ClientAliveInterval {{ seconds }}
    state: present
  register: sshd

- name: Restart service SSHD
  service:
    name: sshd
    state: reloaded
  when: sshd.changed
