# platform = multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Get interfaces
  shell: awk -F":" ' $1!~"^Inter*" &&  $1!~"face.*"{ print $1 }' /proc/net/wireless
  register: wireless_interfaces

- name: Disable interfaces
  shell: ip link set {{ item }} down
  with_items: "{{ wireless_interfaces.stdout_lines }}"

