# platform = multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_rhv,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Get local paths
  shell: find /home/* -type f \( -perm -g+w -or -perm -o+w \) -iname ".*"
  register: hiddenfilepaths
  ignore_errors: True

- name: Change perms
  file:
    path: '{{ item }}'
    mode: g-w,o-w
  with_items:
    - '{{ hiddenfilepaths.stdout_lines }}'
