# platform = multi_platform_fedora,multi_platform_rhel,multi_platform_rhv,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: Ensure disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '\#?PermitRootLogin.*'
    line: PermitRootLogin no
    state: present
  register: sshd
  
- name: Restart service SSHD
  service:
    name: sshd
    state: reloaded
  when: sshd.changed