# platform = multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_rhv,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = high
# disruption = high

- name: Get local paths
  shell: find / -type d \( -perm -o+w \)
  register: paths
  ignore_errors: True

- name: Change perms
  file:
    path:  "{{ item }}"
    mode:  a+t
  with_items:
    -  "{{ paths.stdout_lines }}"
