# platform = multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_rhv,multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Delete "+:" entries in shadow
  lineinfile:
    path: /etc/shadow
    state: absent
    regexp: '^\+:'
